# pubspec.yaml
name: meubolso
description: Aplicativo de Controle de Despesas em Flutter com Firebase

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.5
  cloud_firestore: ^4.7.2
  google_sign_in: ^5.4.0
  pigeon: ^22.6.0
  provider: ^6.0.3
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  fl_chart: ^0.35.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/piggy_bank_icon.png
    - assets/images/intro_image.png
    - assets/images/piggy_bank2_icon.png
